--------------
title: "My Blog"
date: YYYY-MM-DD
author: Ben Lucas
email: lucas.banet@gmail.com
description: > # this means to ignore newlines until "baseurl:"

# social links
twitter_username: @benblucas
github_username:  benblucas

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
----------------
