title: My Blog
author: Ben Lucas
email: lucas.banet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  More content coming soon!

# social links
twitter_username: @benblucas
github_username:  benblucas

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

